default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: jktuukegsqq
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: store_app_development

test:
  <<: *default
  database: store_app_test
